- hosts: all
  become: true
    
  vars:
    roles_path: '.'
    php_version: '7.3'
    php_enablerepo: "remi-php73,epel"

  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
#    - role: geerlingguy.mysql
